"""added user type

Revision ID: 5811127b40d8
Revises: 3438cea17e34
Create Date: 2019-04-27 17:37:07.976909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5811127b40d8'
down_revision = '3438cea17e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usertype', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'usertype')
    # ### end Alembic commands ###
