"""event and event types

Revision ID: 984d93b4eebc
Revises: 5811127b40d8
Create Date: 2019-04-27 18:45:01.132447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984d93b4eebc'
down_revision = '5811127b40d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('url_info', sa.String(length=200), nullable=True),
    sa.Column('geo_fence', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['eventtype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('eventtype')
    # ### end Alembic commands ###
