"""created interests table

Revision ID: f8ca8bf2ed5b
Revises: 4d0079df5f10
Create Date: 2019-04-27 22:24:44.258397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ca8bf2ed5b'
down_revision = '4d0079df5f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_type'], ['event_type.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interests')
    # ### end Alembic commands ###
